version: '3.8'

services:
  scheduledk_postgres:
    image: postgres:13
    container_name: scheduledk_postgres_db
    environment:
      POSTGRES_USER: SCHEDULED_K
      POSTGRES_PASSWORD: ScheduledK123!
      POSTGRES_DB: scheduledk_db
    ports:
      - "5435:5432"
    volumes:
      - scheduledk_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  scheduledk_postgres_data: